// Generated by languages:generate. Edit languages.json.
// oxlint-disable-next-line typescript-eslint/triple-slash-reference
/// <reference path="./vite-assets.d.ts" />
import type { TreeSitterLanguageContribution } from '@singapore-editor/tree-sitter'
import { mapQueryCaptures } from './query-captures'
export const TREE_SITTER_LANGUAGE_CONTRIBUTIONS: readonly TreeSitterLanguageContribution[] = [
  {
    id: 'javascript',
    extensions: ['.cjs', '.js', '.jsx', '.mjs'],
    filenames: [],
    aliases: ['js', 'jsx', 'node'],
    injectionDependencies: ['regex', 'jsdoc'],
    async load() {
      const assets = await Promise.all([
        import('tree-sitter-javascript/tree-sitter-javascript.wasm?url').then(
          (module) => module.default,
        ),
        import('./queries/javascript-highlights.scm?raw').then((module) => module.default),
        import('tree-sitter-javascript/queries/highlights-jsx.scm?raw').then(
          (module) => module.default,
        ),
        import('./queries/javascript-folds.scm?raw').then((module) => module.default),
        import('./queries/jsx-folds.scm?raw').then((module) => module.default),
        import('./queries/javascript-injections.scm?raw').then((module) => module.default),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures(
          [assets[1]!, assets[2]!].join('\n'),
          captureMappings,
        ),
        foldQuerySource: mapQueryCaptures([assets[3]!, assets[4]!].join('\n'), captureMappings),
        injectionQuerySource: mapQueryCaptures([assets[5]!].join('\n'), captureMappings),
      }
    },
  },
  {
    id: 'typescript',
    extensions: ['.cts', '.mts', '.ts'],
    filenames: [],
    aliases: ['ts'],
    injectionDependencies: ['regex', 'jsdoc'],
    async load() {
      const assets = await Promise.all([
        import('tree-sitter-typescript/tree-sitter-typescript.wasm?url').then(
          (module) => module.default,
        ),
        import('./queries/typescript-highlights.scm?raw').then((module) => module.default),
        import('./queries/javascript-highlights.scm?raw').then((module) => module.default),
        import('./queries/typescript-folds.scm?raw').then((module) => module.default),
        import('./queries/javascript-folds.scm?raw').then((module) => module.default),
        import('./queries/javascript-injections.scm?raw').then((module) => module.default),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures(
          [assets[1]!, assets[2]!].join('\n'),
          captureMappings,
        ),
        foldQuerySource: mapQueryCaptures([assets[3]!, assets[4]!].join('\n'), captureMappings),
        injectionQuerySource: mapQueryCaptures([assets[5]!].join('\n'), captureMappings),
      }
    },
  },
  {
    id: 'tsx',
    extensions: ['.tsx'],
    filenames: [],
    aliases: ['typescriptreact'],
    injectionDependencies: ['regex', 'jsdoc'],
    async load() {
      const assets = await Promise.all([
        import('tree-sitter-typescript/tree-sitter-tsx.wasm?url').then((module) => module.default),
        import('./queries/typescript-highlights.scm?raw').then((module) => module.default),
        import('./queries/javascript-highlights.scm?raw').then((module) => module.default),
        import('tree-sitter-javascript/queries/highlights-jsx.scm?raw').then(
          (module) => module.default,
        ),
        import('./queries/typescript-folds.scm?raw').then((module) => module.default),
        import('./queries/javascript-folds.scm?raw').then((module) => module.default),
        import('./queries/jsx-folds.scm?raw').then((module) => module.default),
        import('./queries/javascript-injections.scm?raw').then((module) => module.default),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures(
          [assets[1]!, assets[2]!, assets[3]!].join('\n'),
          captureMappings,
        ),
        foldQuerySource: mapQueryCaptures(
          [assets[4]!, assets[5]!, assets[6]!].join('\n'),
          captureMappings,
        ),
        injectionQuerySource: mapQueryCaptures([assets[7]!].join('\n'), captureMappings),
      }
    },
  },
  {
    id: 'html',
    extensions: ['.htm', '.html'],
    filenames: [],
    aliases: [],
    injectionDependencies: ['javascript', 'css'],
    async load() {
      const assets = await Promise.all([
        import('tree-sitter-html/tree-sitter-html.wasm?url').then((module) => module.default),
        import('tree-sitter-html/queries/highlights.scm?raw').then((module) => module.default),
        import('./queries/html-folds.scm?raw').then((module) => module.default),
        import('tree-sitter-html/queries/injections.scm?raw').then((module) => module.default),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures([assets[1]!].join('\n'), captureMappings),
        foldQuerySource: mapQueryCaptures([assets[2]!].join('\n'), captureMappings),
        injectionQuerySource: mapQueryCaptures([assets[3]!].join('\n'), captureMappings),
      }
    },
  },
  {
    id: 'css',
    extensions: ['.css'],
    filenames: [],
    aliases: [],
    injectionDependencies: [],
    async load() {
      const assets = await Promise.all([
        import('tree-sitter-css/tree-sitter-css.wasm?url').then((module) => module.default),
        import('tree-sitter-css/queries/highlights.scm?raw').then((module) => module.default),
        import('./queries/css-folds.scm?raw').then((module) => module.default),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures([assets[1]!].join('\n'), captureMappings),
        foldQuerySource: mapQueryCaptures([assets[2]!].join('\n'), captureMappings),
        injectionQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
      }
    },
  },
  {
    id: 'json',
    extensions: ['.json'],
    filenames: [],
    aliases: [],
    injectionDependencies: [],
    async load() {
      const assets = await Promise.all([
        import('tree-sitter-json/tree-sitter-json.wasm?url').then((module) => module.default),
        import('tree-sitter-json/queries/highlights.scm?raw').then((module) => module.default),
        import('./queries/json-folds.scm?raw').then((module) => module.default),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures([assets[1]!].join('\n'), captureMappings),
        foldQuerySource: mapQueryCaptures([assets[2]!].join('\n'), captureMappings),
        injectionQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
      }
    },
  },
  {
    id: 'markdown',
    extensions: ['.md', '.markdown'],
    filenames: [],
    aliases: ['md', 'gfm'],
    injectionDependencies: ['html', 'markdown_inline'],
    async load() {
      const assets = await Promise.all([
        import('./grammars/tree-sitter-markdown.wasm?url').then((module) => module.default),
        import('./queries/markdown-highlights.scm?raw').then((module) => module.default),
        import('./queries/markdown-folds.scm?raw').then((module) => module.default),
        import('./queries/markdown-injections.scm?raw').then((module) => module.default),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures([assets[1]!].join('\n'), captureMappings),
        foldQuerySource: mapQueryCaptures([assets[2]!].join('\n'), captureMappings),
        injectionQuerySource: mapQueryCaptures([assets[3]!].join('\n'), captureMappings),
      }
    },
  },
  {
    id: 'markdown_inline',
    extensions: [],
    filenames: [],
    aliases: [],
    injectionDependencies: ['html'],
    async load() {
      const assets = await Promise.all([
        import('./grammars/tree-sitter-markdown-inline.wasm?url').then((module) => module.default),
        import('./queries/markdown-inline-highlights.scm?raw').then((module) => module.default),
        import('./queries/markdown-inline-injections.scm?raw').then((module) => module.default),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures([assets[1]!].join('\n'), captureMappings),
        foldQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
        injectionQuerySource: mapQueryCaptures([assets[2]!].join('\n'), captureMappings),
      }
    },
  },
  {
    id: 'astro',
    extensions: ['.astro'],
    filenames: [],
    aliases: [],
    injectionDependencies: ['typescript', 'css'],
    async load() {
      const assets = await Promise.all([
        import('./grammars/tree-sitter-astro.wasm?url').then((module) => module.default),
        import('./queries/astro-highlights.scm?raw').then((module) => module.default),
        import('./queries/astro-folds.scm?raw').then((module) => module.default),
        import('./queries/astro-injections.scm?raw').then((module) => module.default),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures([assets[1]!].join('\n'), captureMappings),
        foldQuerySource: mapQueryCaptures([assets[2]!].join('\n'), captureMappings),
        injectionQuerySource: mapQueryCaptures([assets[3]!].join('\n'), captureMappings),
      }
    },
  },
  {
    id: 'python',
    extensions: ['.py', '.pyi'],
    filenames: [],
    aliases: ['py'],
    injectionDependencies: [],
    async load() {
      const assets = await Promise.all([
        import('tree-sitter-python/tree-sitter-python.wasm?url').then((module) => module.default),
        import('tree-sitter-python/queries/highlights.scm?raw').then((module) => module.default),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures([assets[1]!].join('\n'), captureMappings),
        foldQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
        injectionQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
      }
    },
  },
  {
    id: 'shellscript',
    extensions: ['.sh', '.bash', '.zsh', '.ksh'],
    filenames: ['.bashrc', '.zshrc'],
    aliases: ['bash', 'sh', 'zsh'],
    injectionDependencies: [],
    async load() {
      const assets = await Promise.all([
        import('tree-sitter-bash/tree-sitter-bash.wasm?url').then((module) => module.default),
        import('tree-sitter-bash/queries/highlights.scm?raw').then((module) => module.default),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures([assets[1]!].join('\n'), captureMappings),
        foldQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
        injectionQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
      }
    },
  },
  {
    id: 'rust',
    extensions: ['.rs'],
    filenames: [],
    aliases: ['rs'],
    injectionDependencies: [],
    async load() {
      const assets = await Promise.all([
        import('tree-sitter-rust/tree-sitter-rust.wasm?url').then((module) => module.default),
        import('tree-sitter-rust/queries/highlights.scm?raw').then((module) => module.default),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures([assets[1]!].join('\n'), captureMappings),
        foldQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
        injectionQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
      }
    },
  },
  {
    id: 'go',
    extensions: ['.go'],
    filenames: [],
    aliases: ['golang'],
    injectionDependencies: [],
    async load() {
      const assets = await Promise.all([
        import('tree-sitter-go/tree-sitter-go.wasm?url').then((module) => module.default),
        import('tree-sitter-go/queries/highlights.scm?raw').then((module) => module.default),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures([assets[1]!].join('\n'), captureMappings),
        foldQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
        injectionQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
      }
    },
  },
  {
    id: 'yaml',
    extensions: ['.yml', '.yaml'],
    filenames: [],
    aliases: ['yml'],
    injectionDependencies: [],
    async load() {
      const assets = await Promise.all([
        import('@tree-sitter-grammars/tree-sitter-yaml/tree-sitter-yaml.wasm?url').then(
          (module) => module.default,
        ),
        import('@tree-sitter-grammars/tree-sitter-yaml/queries/highlights.scm?raw').then(
          (module) => module.default,
        ),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures([assets[1]!].join('\n'), captureMappings),
        foldQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
        injectionQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
      }
    },
  },
  {
    id: 'toml',
    extensions: ['.toml'],
    filenames: ['Cargo.lock'],
    aliases: [],
    injectionDependencies: [],
    async load() {
      const assets = await Promise.all([
        import('@tree-sitter-grammars/tree-sitter-toml/tree-sitter-toml.wasm?url').then(
          (module) => module.default,
        ),
        import('@tree-sitter-grammars/tree-sitter-toml/queries/highlights.scm?raw').then(
          (module) => module.default,
        ),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures([assets[1]!].join('\n'), captureMappings),
        foldQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
        injectionQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
      }
    },
  },
  {
    id: 'c',
    extensions: ['.c', '.h'],
    filenames: [],
    aliases: [],
    injectionDependencies: [],
    async load() {
      const assets = await Promise.all([
        import('tree-sitter-c/tree-sitter-c.wasm?url').then((module) => module.default),
        import('tree-sitter-c/queries/highlights.scm?raw').then((module) => module.default),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures([assets[1]!].join('\n'), captureMappings),
        foldQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
        injectionQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
      }
    },
  },
  {
    id: 'cpp',
    extensions: ['.cpp', '.cc', '.cxx', '.hpp', '.hh', '.hxx'],
    filenames: [],
    aliases: ['c++'],
    injectionDependencies: [],
    async load() {
      const assets = await Promise.all([
        import('tree-sitter-cpp/tree-sitter-cpp.wasm?url').then((module) => module.default),
        import('tree-sitter-c/queries/highlights.scm?raw').then((module) => module.default),
        import('tree-sitter-cpp/queries/highlights.scm?raw').then((module) => module.default),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures(
          [assets[1]!, assets[2]!].join('\n'),
          captureMappings,
        ),
        foldQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
        injectionQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
      }
    },
  },
  {
    id: 'csharp',
    extensions: ['.cs'],
    filenames: [],
    aliases: ['c-sharp', 'cs'],
    injectionDependencies: [],
    async load() {
      const assets = await Promise.all([
        import('tree-sitter-c-sharp/tree-sitter-c_sharp.wasm?url').then((module) => module.default),
        import('tree-sitter-c-sharp/queries/highlights.scm?raw').then((module) => module.default),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures([assets[1]!].join('\n'), captureMappings),
        foldQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
        injectionQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
      }
    },
  },
  {
    id: 'java',
    extensions: ['.java'],
    filenames: [],
    aliases: [],
    injectionDependencies: [],
    async load() {
      const assets = await Promise.all([
        import('tree-sitter-java/tree-sitter-java.wasm?url').then((module) => module.default),
        import('tree-sitter-java/queries/highlights.scm?raw').then((module) => module.default),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures([assets[1]!].join('\n'), captureMappings),
        foldQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
        injectionQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
      }
    },
  },
  {
    id: 'php',
    extensions: ['.php'],
    filenames: [],
    aliases: [],
    injectionDependencies: ['phpdoc'],
    async load() {
      const assets = await Promise.all([
        import('tree-sitter-php/tree-sitter-php.wasm?url').then((module) => module.default),
        import('tree-sitter-php/queries/highlights.scm?raw').then((module) => module.default),
        import('tree-sitter-php/queries/injections.scm?raw').then((module) => module.default),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures([assets[1]!].join('\n'), captureMappings),
        foldQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
        injectionQuerySource: mapQueryCaptures([assets[2]!].join('\n'), captureMappings),
      }
    },
  },
  {
    id: 'lua',
    extensions: ['.lua'],
    filenames: [],
    aliases: [],
    injectionDependencies: ['c'],
    async load() {
      const assets = await Promise.all([
        import('@tree-sitter-grammars/tree-sitter-lua/tree-sitter-lua.wasm?url').then(
          (module) => module.default,
        ),
        import('@tree-sitter-grammars/tree-sitter-lua/queries/highlights.scm?raw').then(
          (module) => module.default,
        ),
        import('@tree-sitter-grammars/tree-sitter-lua/queries/injections.scm?raw').then(
          (module) => module.default,
        ),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures([assets[1]!].join('\n'), captureMappings),
        foldQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
        injectionQuerySource: mapQueryCaptures([assets[2]!].join('\n'), captureMappings),
      }
    },
  },
  {
    id: 'svelte',
    extensions: ['.svelte'],
    filenames: [],
    aliases: [],
    injectionDependencies: ['typescript', 'css'],
    async load() {
      const assets = await Promise.all([
        import('tree-sitter-svelte/tree-sitter-svelte.wasm?url').then((module) => module.default),
        import('tree-sitter-svelte/queries/highlights.scm?raw').then((module) => module.default),
        import('tree-sitter-svelte/queries/folds.scm?raw').then((module) => module.default),
        import('./queries/svelte-injections.scm?raw').then((module) => module.default),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures([assets[1]!].join('\n'), captureMappings),
        foldQuerySource: mapQueryCaptures([assets[2]!].join('\n'), captureMappings),
        injectionQuerySource: mapQueryCaptures([assets[3]!].join('\n'), captureMappings),
      }
    },
  },
  {
    id: 'sql',
    extensions: ['.sql'],
    filenames: [],
    aliases: [],
    injectionDependencies: [],
    async load() {
      const assets = await Promise.all([
        import('./grammars/tree-sitter-sql.wasm?url').then((module) => module.default),
        import('./queries/sql-highlights.scm?raw').then((module) => module.default),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures([assets[1]!].join('\n'), captureMappings),
        foldQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
        injectionQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
      }
    },
  },
  {
    id: 'mdx',
    extensions: ['.mdx'],
    filenames: [],
    aliases: [],
    injectionDependencies: ['markdown_inline', 'markdown'],
    async load() {
      const assets = await Promise.all([
        import('./grammars/tree-sitter-mdx.wasm?url').then((module) => module.default),
        import('./queries/mdx-highlights.scm?raw').then((module) => module.default),
        import('./queries/mdx-injections.scm?raw').then((module) => module.default),
      ])
      return {
        wasmUrl: assets[0]!,
        highlightQuerySource: mapQueryCaptures([assets[1]!].join('\n'), captureMappings),
        foldQuerySource: mapQueryCaptures([].join('\n'), captureMappings),
        injectionQuerySource: mapQueryCaptures([assets[2]!].join('\n'), captureMappings),
      }
    },
  },
]
const captureMappings: Readonly<Record<string, string>> = {
  escape: 'string.escape',
  boolean: 'constant.builtin',
  label: 'property',
  delimiter: 'punctuation.delimiter',
  module: 'namespace',
  'module.builtin': 'namespace',
  method: 'function.method',
  'method.call': 'function.method',
  field: 'property',
  parameter: 'variable.parameter',
  conditional: 'keyword.control',
  repeat: 'keyword.control',
  preproc: 'keyword',
  error: 'tag.error',
  'text.strike': 'text.literal',
  'text.underline': 'text.reference',
  storageclass: 'keyword.storage',
}
