import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { Language, Parser } from 'web-tree-sitter'
import { mapQueryCaptures } from '../src/query-captures.ts'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const manifest = JSON.parse(await readFile(resolve(root, 'languages.json'), 'utf8'))
const check = process.argv.includes('--check')
const quote = JSON.stringify
const ids = new Set()
const aliases = new Set()
await Parser.init()
const locks = []
const notices = []
const assetPath = (name) => resolve(root, name.startsWith('.') ? 'src' : 'node_modules', name)
const digest = (bytes) => createHash('sha256').update(bytes).digest('hex')

for (const language of manifest.languages) {
  assert(!ids.has(language.id), `Duplicate language: ${language.id}`)
  ids.add(language.id)
  for (const alias of [language.id, ...language.aliases]) {
    assert(!aliases.has(alias), `Ambiguous alias: ${alias}`)
    aliases.add(alias)
  }
  const files = [language.wasm, ...Object.values(language.queries).flat()]
  const hashes = await Promise.all(
    files.map(async (file) => ({ file, sha256: digest(await readFile(assetPath(file))) })),
  )
  const grammar = await Language.load(await readFile(assetPath(language.wasm)))
  const source = manifest.sources[language.source]
  const sourceFiles = source.package
    ? await hashSourceFiles(resolve(root, 'node_modules', source.package))
    : []
  const queries = await Promise.all(
    Object.entries(language.queries).map(async ([kind, paths]) => {
      const source = (
        await Promise.all(paths.map((file) => readFile(assetPath(file), 'utf8')))
      ).join('\n')
      return { kind, sha256: digest(mapQueryCaptures(source, manifest.captureMappings)) }
    }),
  )
  locks.push({
    id: language.id,
    parserABI: grammar.abiVersion,
    source,
    sourceFiles,
    files: hashes,
    queries,
  })
}
for (const [name, source] of Object.entries(manifest.sources)) {
  if (!source.package) {
    notices.push(
      `${name}\n${source.repository}@${source.revision}\n${await readFile(resolve(root, 'notices', `${name}.txt`), 'utf8')}`,
    )
    continue
  }
  const directory = resolve(root, 'node_modules', source.package)
  const pkg = JSON.parse(await readFile(resolve(directory, 'package.json'), 'utf8'))
  assert.equal(pkg.version, source.version, `Source version changed: ${name}`)
  const license = await readFile(resolve(directory, source.licenseFile ?? 'LICENSE'), 'utf8')
  notices.push(`${name}@${source.version}\n${license}`)
}

const loaders = manifest.languages
  .map((language) => {
    const imports = [language.wasm, ...Object.values(language.queries).flat()]
    const parts = [`wasmUrl: assets[0]!`]
    let index = 1
    for (const [kind, sources] of Object.entries(language.queries)) {
      const key = {
        highlights: 'highlightQuerySource',
        folds: 'foldQuerySource',
        injections: 'injectionQuerySource',
      }[kind]
      parts.push(
        `${key}: mapQueryCaptures([${sources.map(() => `assets[${index++}]!`).join(', ')}].join('\\n'), captureMappings)`,
      )
    }
    const metadata = {
      id: language.id,
      extensions: language.extensions,
      filenames: language.filenames,
      aliases: language.aliases,
      injectionDependencies: language.injectionDependencies,
    }
    return `{ ${quote(metadata).slice(1, -1)}, async load() {\nconst assets = await Promise.all([\n${imports.map((file, index) => `import(${quote(file + (index === 0 ? '?url' : '?raw'))}).then(module => module.default)`).join(',\n')}\n]);\nreturn { ${parts.join(', ')} };\n} }`
  })
  .join(',\n')
const outputs = new Map([
  [
    'src/catalog.generated.ts',
    `// Generated by languages:generate. Edit languages.json.\n// oxlint-disable-next-line typescript-eslint/triple-slash-reference\n/// <reference path="./vite-assets.d.ts" />\nimport type { TreeSitterLanguageContribution } from '@singapore-editor/tree-sitter'\nimport { mapQueryCaptures } from './query-captures'\nexport const TREE_SITTER_LANGUAGE_CONTRIBUTIONS: readonly TreeSitterLanguageContribution[] = [\n${loaders}\n]\nconst captureMappings: Readonly<Record<string, string>> = ${quote(manifest.captureMappings)}`,
  ],
  [
    'src/metadata.ts',
    `// Generated by languages:generate. Contains no grammar imports.\nexport const TREE_SITTER_LANGUAGE_METADATA = ${quote(manifest.languages.map(({ id, extensions, filenames, aliases, injectionDependencies, capabilities }) => ({ id, extensions, filenames, aliases, injectionDependencies, capabilities })))} as const\n`,
  ],
  [
    'languages.lock.json',
    JSON.stringify(
      { schemaVersion: 1, manifestHash: digest(JSON.stringify(manifest)), languages: locks },
      null,
      2,
    ) + '\n',
  ],
  ['NOTICE', notices.join('\n\n')],
])
// Validate every input before writing any generated output.
for (const [file, content] of outputs) {
  if (/\.(ts|json)$/.test(file)) outputs.set(file, formatTypeScript(file, content))
}
for (const [file, content] of outputs) {
  const path = resolve(root, file)
  if (check) {
    assert.equal(await readFile(path, 'utf8'), content, `Stale generated file: ${file}`)
    continue
  }
  await mkdir(dirname(path), { recursive: true })
  await writeFile(path, content)
}
console.log(`${check ? 'Checked' : 'Generated'} ${manifest.languages.length} lazy languages`)

function formatTypeScript(file, input) {
  const result = spawnSync(resolve(root, 'node_modules/.bin/oxfmt'), ['--stdin-filepath', file], {
    cwd: root,
    input,
    encoding: 'utf8',
  })
  assert.equal(result.status, 0, result.stderr)
  return result.stdout
}

async function hashSourceFiles(directory, relative = '') {
  const entries = await readdir(resolve(directory, relative), { withFileTypes: true })
  const files = []
  for (const entry of entries) {
    const name = relative ? `${relative}/${entry.name}` : entry.name
    if (
      entry.isDirectory() &&
      [
        'src',
        'typescript',
        'tsx',
        'php',
        'php_only',
        'tree-sitter-markdown',
        'tree-sitter-markdown-inline',
        'tree_sitter',
        'common',
      ].includes(entry.name)
    ) {
      files.push(...(await hashSourceFiles(directory, name)))
      continue
    }
    if (!entry.isFile() || !/\.(c|cc|h|json|js)$/.test(name)) continue
    files.push({ file: name, sha256: digest(await readFile(resolve(directory, name))) })
  }
  return files.sort((left, right) => left.file.localeCompare(right.file, 'en'))
}
