export {
  createEditorConsoleLogger,
  createEditorConsoleLoggingPlugin,
  createEditorLoggingPlugin,
} from './logging'
export {
  bracketJumpTargetOffset,
  createBracketMatchPlugin,
  createDocumentLinkPlugin,
  createMergeConflictDocumentText,
  createMergeConflictPlugin,
  createOccurrenceHighlightPlugin,
  Editor,
  EDITOR_BRACKET_MATCH_PLUGIN_ID,
  EDITOR_DOCUMENT_LINK_PLUGIN_ID,
  EDITOR_OCCURRENCE_HIGHLIGHT_PLUGIN_ID,
  EDITOR_MERGE_CONFLICT_FEATURE,
  EDITOR_MERGE_CONFLICT_FEATURE_ID,
  findBracketMatchAtCaret,
  observeEditorMountTiming,
  parseMergeConflicts,
  resolveMergeConflict,
} from './editor'
export type {
  BracketMatch,
  EditorBracketMatchPluginOptions,
  EditorDocumentLinkPluginOptions,
  EditorOccurrenceHighlightPluginOptions,
  EditorSuspiciousCharactersOptions,
  SuspiciousCharacterKind,
  SuspiciousCharacterRange,
} from './editor'
export { suspiciousCharacterRanges } from './editor'
export { createEditorPreparedDocument } from './editor/preparedDocument'
export type {
  CreateEditorPreparedDocumentOptions,
  EditorPreparedDocument,
  EditorPreparedDocumentMatch,
  EditorPreparedDocumentPayload,
  EditorPreparedHighlighterTransfer,
  EditorPreparedStageOutcome,
  EditorPreparedStageRequest,
  EditorPreparedStructuralConfiguration,
  EditorPreparedStructuralTransfer,
  EditorPreparedTagValue,
  EditorPreparedTabSizePolicy,
} from './editor/preparedDocument'
export { createEditorOptionSync, EDITOR_OPTION_DESCRIPTORS } from './editor/optionDescriptors'
export type {
  EditorControlledOptionName,
  EditorControlledSelection,
  EditorOptionDescriptor,
  EditorOptionSync,
} from './editor/optionDescriptors'
export {
  Anchor,
  anchorAfter,
  anchorAt,
  anchorBefore,
  applyBatchToPieceTable,
  acquireDocumentMutationLease,
  beginReverseDocumentTransactionSequence,
  commitPreparedDocumentTransaction,
  commitPreparedDocumentTransactionSequenceSegment,
  completePreparedDocumentTransactionSequence,
  completeReverseDocumentTransactionSequence,
  createDocumentSession,
  createDocumentLogicalRevisionScope,
  createDocumentTextSnapshot,
  createEditorBufferSession,
  createEditorTextBuffer,
  createEditorViewSession,
  createPieceTableSnapshot,
  createPieceTableWalker,
  createStaticDocumentSession,
  createStringTextSnapshot,
  deleteFromPieceTable,
  diffPieceTableSnapshots,
  documentTextRoundTripStatus,
  forEachPieceTableTextChunk,
  getPieceTableLength,
  getDocumentMutationLeaseState,
  readPieceTableTextRange,
  insertIntoPieceTable,
  materializePieceTableFullText,
  offsetToPoint,
  pieceTableSnapshotsHaveSameText,
  pieceTableDocumentText,
  pointToOffset,
  resolveAnchor,
  prepareDocumentTransaction,
  prepareDocumentTransactionSequence,
  releaseDocumentMutationLease,
  releaseDocumentTransactionReceipt,
  reverseDocumentTransaction,
  reverseNextDocumentTransactionSequenceSegment,
  rotateDocumentSyncSegment,
  sealDocumentTransactionReceipt,
  subscribeDocumentMutationLeaseState,
} from './public/document'
export { createHistoryViewer, layoutHistoryGraph } from './historyViewer'
export type {
  HistoryComparison,
  HistoryComparisonSide,
  HistoryGraphLayout,
  HistoryGraphLayoutEdge,
  HistoryGraphLayoutNode,
  HistoryViewer,
  HistoryViewerOptions,
  HistoryViewerState,
} from './historyViewer'
export {
  createEditorCapabilityToken,
  createEditorLanguageFeatureToken,
  registerAmbientEditorPlugin,
  EDITOR_FIND_FEATURE,
  EDITOR_FIND_FEATURE_ID,
  EDITOR_MINIMAP_FEATURE,
  EDITOR_MINIMAP_FEATURE_ID,
  EditorDecorationStore,
  editorLanguageConfiguration,
  projectDecorationRangeThroughEdits,
  registerEditorLanguageConfiguration,
} from './public/extensions'
export type {
  EditorAutoClosingPair,
  EditorBlockCommentTokens,
  EditorBracketPair,
  EditorCommentTokens,
  EditorDecoration,
  EditorDecorationRange,
  EditorDecorationSpec,
  EditorDecorationSurface,
  EditorEnterAction,
  EditorFindFeature,
  EditorFoldingRules,
  EditorIndentationRules,
  EditorLanguageConfiguration,
  EditorOnEnterRule,
} from './public/extensions'
export {
  applyEditorTheme,
  darkenEditorColor,
  editorColorReference,
  editorColorValue,
  editorThemesEqual,
  firstEditorColor,
  lightenEditorColor,
  mergeEditorThemes,
  registerEditorColor,
  transparentEditorColor,
} from './public/rendering'
export {
  createSemanticTokenLayer,
  SEMANTIC_TOKEN_Z_INDEX,
  type SemanticTokenLayer,
  type SemanticTokenLayerController,
  type SemanticTokenLayerOptions,
} from './public/extensions'
export {
  createEditorScopeStyles,
  createEditorRuntimeSessionId,
  createEditorSyntaxSession,
  createEmptySyntaxResult,
  createEmptySyntaxSession,
  createSemanticTokenStyles,
  createSyntaxLanguageConfiguration,
  createSyntaxProjectionTag,
  createSyntaxSnapshotTag,
  isEditorSyntaxLanguage,
  styleForTreeSitterCapture,
  treeSitterCapturesToEditorTokens,
} from './public/syntax'
export type {
  EditorScopeStyleRule,
  EditorScopeStyles,
  SemanticTokenDropReason,
  SemanticTokenPayload,
  SemanticTokenPushResult,
  SemanticTokenRangeRequest,
  SemanticTokenSpan,
  SemanticTokenStyleOptions,
  SemanticTokenStyles,
} from './public/syntax'
export {
  defaultEditorCommandPacks,
  defaultEditorKeyBindings,
  defaultEditorKeymapLayers,
  editorCommandPackForCommand,
  editorKeyBindings,
  editorKeyBindingsFromLayers,
  editorKeymapLayerForCommandPack,
  editorKeymapLayers,
  editorKeymapLayersForBindings,
  editorKeymapLayersForCommandPacks,
  filterEditorKeymapLayersByCommandPacks,
  readonlySafeEditorCommandPacks,
} from './editor/keymap'
export type {
  AnchorBias,
  AnchorLiveness,
  AcquireDocumentMutationLeaseResult,
  BeginReverseDocumentTransactionSequenceResult,
  CompletePreparedDocumentSequenceResult,
  CompleteReverseDocumentTransactionSequenceResult,
  DocumentChangesSinceSyncPoint,
  DocumentLogicalRevisionScope,
  DocumentMutationLease,
  DocumentMutationLeaseState,
  DocumentMutationLeaseStateListener,
  DocumentSession,
  DocumentSessionApplyEditsOptions,
  DocumentSessionChange,
  DocumentSessionChangeKind,
  EditorHistoryBarrier,
  EditorHistoryGraph,
  EditorHistoryGraphNode,
  EditorTextBufferOptions,
  HistoryNodeId,
  DocumentSessionEditHistoryMode,
  DocumentSessionEditSelection,
  DocumentSessionSelectionOptions,
  DocumentSessionSelectionRange,
  DocumentSyncPoint,
  DocumentSyncSegment,
  DocumentTextRoundTripIssue,
  DocumentTextRoundTripStatus,
  DocumentTransactionCommitOptions,
  DocumentTransactionCommitTarget,
  DocumentTransactionHistory,
  DocumentTransactionReceipt,
  DocumentTransactionSequenceReverseCursor,
  DocumentTransactionSequenceSegmentInput,
  DocumentTextSnapshot,
  EditorBufferSession,
  EditorDocument,
  EditorTextBuffer,
  EditorTextBufferChange,
  EditorTextBufferChangeListener,
  EditorTimingMeasurement,
  EditorViewMetadataValue,
  EditorViewScrollPosition,
  EditorViewSession,
  PieceTableAnchor,
  PieceTableDocumentTextOptions,
  PieceTableEdit,
  PieceTableSnapshot,
  PieceTableWalker,
  PieceTableWalkerChunk,
  Point,
  ResolvedAnchor,
  PreparedDocumentCommitResult,
  PreparedDocumentSequenceSegmentCommitResult,
  PreparedDocumentTransaction,
  PreparedDocumentTransactionSequence,
  ReleaseDocumentMutationLeaseResult,
  ReleaseDocumentTransactionResult,
  ReverseDocumentTransactionResult,
  ReverseDocumentTransactionSequenceSegmentResult,
  RotateDocumentSyncSegmentResult,
  SealDocumentTransactionResult,
  SelectionAffinity,
  TextEdit,
  TextSnapshot,
} from './public/document'
export type {
  EditorChangeHandler,
  EditorCommandContext,
  EditorCommandId,
  EditorDocumentMode,
  EditorEditability,
  EditorEditHistoryMode,
  EditorEditInput,
  EditorEditOptions,
  EditorEditSelection,
  EditorOpenDocumentOptions,
  EditorOptions,
  EditorRangeDecoration,
  EditorScrollMode,
  EditorScrollPosition,
  EditorSelectionRevealOptions,
  EditorSelectionRevealTarget,
  EditorSelectionSyncMode,
  EditorSetSelectionOptions,
  EditorSetTextOptions,
  EditorState,
  EditorSyntaxSessionFactory,
  EditorSyntaxStatus,
  HighlightRegistry,
} from './editor'
export type {
  EditorCommandPack,
  EditorKeyBinding,
  EditorKeymapLayer,
  EditorKeymapLayerSource,
  EditorKeymapOptions,
} from './editor/keymap'
export type {
  EditorCapabilityContribution,
  EditorCapabilityContributionContext,
  EditorCapabilityContributionProvider,
  EditorCommandHandler,
  EditorCommandContribution,
  EditorCommandContributionContext,
  EditorCommandContributionProvider,
  EditorCapabilityToken,
  EditorDecorationContribution,
  EditorDecorationContributionContext,
  EditorDecorationContributionProvider,
  EditorEditContribution,
  EditorEditContributionContext,
  EditorEditContributionProvider,
  EditorDisposable,
  EditorGutterContribution,
  EditorGutterRowContext,
  EditorGutterWidthContext,
  EditorHighlighterProvider,
  EditorHighlighterSession,
  EditorHighlighterSessionOptions,
  EditorHighlightResult,
  EditorInitialHighlightStatus,
  EditorInitialPaintEvent,
  EditorInjectedTextRow,
  EditorInjectedTextRowProvider,
  EditorInjectedTextRowProviderContext,
  EditorLanguageFeatureSelector,
  EditorLanguageFeatureToken,
  EditorLogEditorContext,
  EditorLogError,
  EditorLogEvent,
  EditorLogInput,
  EditorLogger,
  EditorLogLevel,
  EditorMinimapDecoration,
  EditorMinimapDecorationPosition,
  EditorMinimapFeature,
  EditorMinimapSectionHeaderStyle,
  EditorMountedChunkPaintJSON,
  EditorMountedChunkPaintPartJSON,
  EditorOverlaySide,
  EditorPlugin,
  EditorPluginContext,
  EditorPluginLifecycleState,
  EditorResolvedSelection,
  EditorSelectionRange,
  EditorTrackedRanges,
  EditorThemeJSON,
  EditorTokenStyleJSON,
  EditorViewContribution,
  EditorViewContributionContext,
  EditorViewContributionProvider,
  EditorViewContributionUpdateKind,
  EditorViewportSnapshot,
  EditorViewportSnapshotJSON,
  EditorViewSnapshot,
  EditorViewSnapshotJSON,
  EditorVisibleChunkSnapshot,
  EditorVisibleChunkSnapshotJSON,
  EditorVisibleGutterLayoutJSON,
  EditorVisiblePaintCapture,
  EditorVisiblePaintLayer,
  EditorVisiblePaintRectangle,
  EditorVisiblePaintChunkJSON,
  EditorVisiblePaintRowJSON,
  EditorVisiblePaintRunJSON,
  EditorVisibleRowSnapshot,
  EditorVisibleRowSnapshotJSON,
  EditorVisibleSnapshot,
  EditorVisibleSnapshotJSON,
} from './public/extensions'
export type { BrowserTextMetrics } from './virtualization'
export type {
  EditorColorDefaults,
  EditorColorId,
  EditorColorTransform,
  EditorColorValue,
  EditorCursorLineHighlightOptions,
  EditorSyntaxTheme,
  EditorSyntaxThemeColor,
  EditorTheme,
  EditorThemeType,
  HiddenCharactersMode,
  MaterializedInlineRow,
  RangeText,
  TextContent,
  VirtualizedFoldMarker,
  VirtualizedTextHighlightRange,
  VirtualizedTextHighlightStyle,
  VirtualizedTextRowDecoration,
} from './public/rendering'
export type {
  BracketInfo,
  EditorSyntaxCapture,
  EditorSyntaxDegradedState,
  EditorSyntaxEditSummary,
  EditorSyntaxError,
  EditorSyntaxInjection,
  EditorSyntaxLanguageId,
  EditorSyntaxLanguageConfiguration,
  EditorSyntaxMode,
  EditorSyntaxProjectionTag,
  EditorSyntaxProvider,
  EditorSyntaxRange,
  EditorSyntaxResult,
  EditorSyntaxResultOptions,
  EditorSyntaxServiceRequest,
  EditorSyntaxSession,
  EditorSyntaxFoldingSupport,
  EditorSyntaxSessionOptions,
  EditorSyntaxSnapshotTag,
  FoldRange,
} from './public/syntax'
export type { EditorToken, EditorTokenStyle } from './tokens'
export { EditorTokenStore, toEditorTokenStore } from './syntax/tokenStore'
export type { EditorTokenInput, EditorTokenStoreOrigin } from './syntax/tokenStore'
export type {
  CreateMergeConflictDocumentTextOptions,
  EditorMergeConflictFeature,
  EditorMergeConflictPluginOptions,
  MergeConflictRegion,
  MergeConflictResolution,
  MergeConflictResolutionResult,
  MergeConflictSide,
  TextOffsetRange,
} from './editor'
