/*
 * Writes src/worker/bundledLibraries.ts: one lazy import per `lib.*.d.ts` in the installed
 * TypeScript, so the worker ships the standard library it was built against and loads only the
 * files a project's reference closure names. Re-run after upgrading `typescript`;
 * test/libraries.test.ts fails until the table matches the installed set.
 */

import { readdirSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'

const directory = dirname(createRequire(import.meta.url).resolve('typescript'))
const names = readdirSync(directory)
  .filter((entry) => entry.startsWith('lib.') && entry.endsWith('.d.ts'))
  .toSorted()

const entries = names.map((name) => `  '${name}': () => import('typescript/lib/${name}?raw'),`)
const source = `// Generated by scripts/generate-bundled-libraries.ts. Do not edit.

export const BUNDLED_LIBRARY_FILES: Readonly<
  Record<string, () => Promise<{ readonly default: string }>>
> = {
${entries.join('\n')}
}
`
writeFileSync(join(import.meta.dirname, '../src/worker/bundledLibraries.ts'), source)
console.log(`${names.length} library files`)
